language: python
arch:
  - amd64
  - ppc64le
python:
  - '2.7'
  - '3.9'

install: pip install -r dev-requirements.txt

script:
  - make clean
  - make pep8
  - make flake8
  - make check
  - make unittest

notifications:
  email:
    - eosplus-dev@arista.com

after_success:
  coveralls
